### ISSUE TITLE
dom和GSit不兼容

### ISSUE THREAD

**Issue by shidang233** [ColdeZhang/Dominion#13]
**BUG描述**

@𐂂 未 央 鹿 鸣 
dom和GSit-1.10.0.jar不适配，若有玩家骑在一个玩家的头上玩家就不能使用领地传送功能了，简单说就是玩家头上不能有玩家有的话不能传送（提示成功传送实际没传送）

**复现方式**

Bug复现步骤：

1.装个GSit
2.让玩家骑在你的头上
3.dom tp 传送
4.提示成功了实际还在原地

**正常情况的表现**

正常情况下的表现应该是怎样的

**截图**

（可选）。

**运行环境:**

- 服务器系统：linux
- 服务端核心：paper
- 服务端版本：1.20.6
- 插件版本：最新的（刚下的）

**补充信息**

无错误日志

**Comment by ColdeZhang** [comment]
其他传送类插件能否正常传送？ 比如 ess 或者 cmi 的 tpa

**Comment by ColdeZhang** [comment]
由于缺少补充信息，此issue将在一天后被关闭。

**Comment by LeafletXD** [comment]
此问题在res上也可以复现，不清楚是Gsit的有意设计，或是某种bug

**Comment by LeafletXD** [comment]
> 此问题在res上也可以复现，不清楚是Gsit的有意设计，或是某种bug

tpa那些传送没试过

**Comment by LeafletXD** [comment]
> 由于缺少补充信息，此issue将在一天后被关闭。

此问题在res上也可以复现，不清楚是Gsit的有意设计，或是某种bug

**Comment by ColdeZhang** [comment]
初步认为是传送的时候没有移除 passenger 导致的。
虽然Bukkit提供了相关接口可以在传送之前检查实体身上是否有另外的实体，然后将其他实体先移除后再传送。但是原则上来说既然 GSit 允许玩家乘坐在玩家身上那么其也应该考虑传送时的情况，作为其他插件的开发者没有理由和责任为 GSit 擦屁股检查这种边界情况。

> 地狱门/末地折跃门之类的原版传送，在传送带有乘客的实体的时候也是这么做的，先将实体弹出，然后分别传送过去后再重新附加到原来的实体上。
