### ISSUE TITLE
告示牌不恢复问题

### ISSUE THREAD

**Issue by 365KW** [ColdeZhang/Dominion#16]
**BUG描述**

当破坏权限未打开时 访客破坏告示牌 告示牌上的内容无法恢复

**复现方式**

Bug复现步骤：

1. 在一处有告示牌的领地 请确保自己没有权限
2. 破坏有内容的告示牌
3. 告示牌又重新回来了 但是其内容未能恢复

**正常情况的表现**

在破坏后重新生成一样内容的告示牌

**运行环境:**

- 服务器系统：Linux
- 服务端核心：Paper&Spigot
- 服务端版本：1.21
- 插件版本：2.6.2

**Comment by ColdeZhang** [comment]
请尝试重新登陆游戏，然后观察文字是否恢复。

另：请尝试一下旗帜是否存在相似问题（打掉后旗帜恢复，但是花纹丢失）

**Comment by ColdeZhang** [comment]
该问题在 Folia 1.21 无法复现，请确认存在问题的是 paper 还是 spigot

https://github.com/user-attachments/assets/5965d712-6419-49dc-9bd0-97dd9c58996e

**Comment by ColdeZhang** [comment]
另请关注一下客户端版本与服务端是否一致，某些情况下viaverion版本互通可能会导致这样的方块数据显示错误问题。
