### ISSUE TITLE
风弹会将领地内的生物弹飞

### ISSUE THREAD

**Issue by gghjgdyhtd** [ColdeZhang/Dominion#17]
**BUG描述**

玩家向领地内投掷风弹会将领地内的生物弹飞

Bug复现步骤：
1. 玩家向领地内投掷风弹
2. 生物或实体被弹飞
3. 通过这种方式可以将生物不受限制运出领地

**运行环境:**
- 服务器系统：win
- 服务端核心：Leaves
- 服务端版本：1.21
- 插件版本：2.7.2

**Comment by ColdeZhang** [comment]
麻烦验证一下关掉玩家的 `投掷型武器` 权限后是否还可以使用风弹

**Comment by gghjgdyhtd** [comment]
> 麻烦验证一下关掉玩家的 权限后是否还可以使用风弹`投掷型武器`

我测试的时候确认这个选项对访客是关闭的，风弹只会在接触到方块或实体停下来才会提示我没有投掷型武器权限，实际上生物或实体已经被击飞了

**Comment by gghjgdyhtd** [comment]
> > > 麻烦验证一下关掉玩家的 权限后是否还可以使用风弹`投掷型武器`
> > 
> > 
> > 我测试的时候确认这个选项对访客是关闭的，风弹只会在接触到方块或实体停下来才会提示我没有投掷型武器权限，实际上生物或实体已经被击飞了
> 
> 风弹伤害呢，大概就是没有伤害但是有击退？

对的，这点忘说了，风弹不会伤害领地内的生物，但是会击飞生物位移

**Comment by ColdeZhang** [comment]
> > > > 麻烦验证一下关掉玩家的 权限后是否还可以使用风弹`投掷型武器`
> 
> > > 
> 
> > > 
> 
> > > 我测试的时候确认这个选项对访客是关闭的，风弹只会在接触到方块或实体停下来才会提示我没有投掷型武器权限，实际上生物或实体已经被击飞了
> 
> > 
> 
> > 风弹伤害呢，大概就是没有伤害但是有击退？
> 
> 
> 
> 对的，这点忘说了，风弹不会伤害领地内的生物，但是会击飞生物位移

好的 情况清楚了
我要去bukkit或者spigot下咨询一下，因为我是直接取消抛射物的碰撞权限按理来说击退效果也不会产生，所以我怀疑是核心相关的bug

**Comment by ColdeZhang** [comment]
该漏洞理论已在 v2.8.2-beta 72a5a84 修复，如验证无问题请关闭此issue。
