### ISSUE TITLE
沙子等重力方块可以无限制坠落至领地

### ISSUE THREAD

**Issue by gghjgdyhtd** [ColdeZhang/Dominion#18]
**BUG描述**
沙子等重力方块可以无限制坠落至领地

Bug复现步骤：

1. 玩家搭至领地上方
2. 在领地范围之外悬空放置沙子使沙子下落至领地内
3. 完成对领地的破坏

**运行环境:**

- 服务器系统：win
- 服务端核心：Leaves
- 服务端版本：1.21
- 插件版本：2.7.2

**Comment by ColdeZhang** [comment]
你觉得应该如何处理重力方块比较好？是直接干掉还是变成掉落物，还是在领地边界变成实体方块

**Comment by ColdeZhang** [comment]
> > 你觉得应该如何处理重力方块比较好？是直接干掉还是变成掉落物，还是在领地边界变成实体方块
> 
> 在边界变成实体方块？或者在配置文件中抉择？

从避免熊服的角度出发，个人觉得直接干掉比较好。后两种都会造成一定的熊服效果（大量掉落物造成实体卡顿、漫天方块清理困难）。

**Comment by gghjgdyhtd** [comment]
> > > 你觉得应该如何处理重力方块比较好？是直接干掉还是变成掉落物，还是在领地边界变成实体方块
> > 
> > 
> > 在边界变成实体方块？或者在配置文件中抉择？
> 
> 从避免熊服的角度出发，个人觉得直接干掉比较好。后两种都会造成一定的熊服效果（大量掉落物造成实体卡顿、漫天方块清理困难）。

如果直接干掉或许过度影响了原版特性，这样的话我更倾向于将重力方块变成掉落物，就像原版重力方块下落遇到火把会直接变成掉落物，且掉落物原版中5分钟后自动清理，如果熊孩子恶意卡服者这个绝对不是个好办法，都不如直接将箱子里的物品一股脑丢出来影响大

**Comment by 365KW** [comment]
对于这种 最好搞个监听实体进入事件 sand下落时候会变成实体类吧

**Comment by ColdeZhang** [comment]
该问题已在 v2.8.1-beta 99405c3 实现，如验证无问题请关闭此 issue
