### ISSUE TITLE
优化领地的进出提示

### ISSUE THREAD

**Issue by gghjgdyhtd** [ColdeZhang/Dominion#19]
**新功能是否和BUG有关？**

否

**新功能表述**

如果领地的主人修改了进出领地的提示，那么其他玩家想要寻找领地主人获取领地权限就无从下手了，希望提示后缀强制附上领地的主人名字

**新功能实现方案**

在配置文件中添加在领地进出提示后缀强制附上领地的主人名字的选项开关

**Comment by ColdeZhang** [comment]
站在领地内的时候可以使用 `/dom info` 查看领地信息

**Comment by gghjgdyhtd** [comment]
> 站在领地内的时候可以使用 查看领地信息`/dom info`

当领地的主人关闭了领地的移动权限，这个指令是无效的

**Comment by ColdeZhang** [comment]
> > 站在领地内的时候可以使用 查看领地信息`/dom info`
> 
> 当领地的主人关闭了领地的移动权限，这个指令是无效的

有道理，但是此信息在绝大多数情况下是冗余的。需要一种更好的方式来解决此问题。

**Comment by gghjgdyhtd** [comment]
> > > 站在领地内的时候可以使用 查看领地信息`/dom info`
> > 
> > 
> > 当领地的主人关闭了领地的移动权限，这个指令是无效的
> 
> 有道理，但是此信息在绝大多数情况下是冗余的。需要一种更好的方式来解决此问题。

或许对于领地主人来说是一条冗余的信息，但对于其他玩家来说能通过这些信息快速找到领地主人，也不需要在公屏中等待可能永远没有答复的答复，亦或是恶意圈地，玩家也能迅速识别领地主人报告给管理，而不是等管理来查询，对于管理员来说办事效率会高很多

**Comment by ColdeZhang** [comment]
> dom info后面加上领地名称就能获取 这个更好吧

这个功能的话 现在就有

**Comment by 365KW** [comment]
就是不用进入领地获取名称? 看这个需要的表述

**Comment by ColdeZhang** [comment]
> 就是不用进入领地获取名称? 看这个需要的表述

嗯 没错 /dom info 后面可以指定具体要查看的领地名称

**Comment by ColdeZhang** [comment]
> 就是不用进入领地获取名称? 看这个需要的表述

嗯 没错 /dom info 后面可以指定具体要查看的领地名称

**Comment by 365KW** [comment]
那就得想办法 把名称塞到游戏中

**Comment by ColdeZhang** [comment]
c132f52 提示消息新增占位符支持，可在服务器规章制度中要求所有领地必须插入 `{OWNER}` 占位符
通过制度实现强制展示领地所有人的需求
