### ISSUE TITLE
怪物进入领地规则

### ISSUE THREAD

**Issue by 365KW** [ColdeZhang/Dominion#2]
**新功能是否和BUG有关？**

不相关

**新功能表述**

对于服务器领地而言 我的服务器玩家认为我们很需要一个关于怪物的功能 Res插件里有关于怪物刷新的 插件里有一个伤害限制功能已经很棒了 但是玩家们需要防止怪物进入设置 例如1.21的蠹虫机 熊孩子在领地旁边建造一个全部流进领地真的让人苦不堪言=(

**新功能实现方案**

对于这种功能 也许org.bukkit.entity中的EntitySpawnEvent事件的可以帮到你  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/package-summary.html
以EntitySpawnEvent可以限制生物在领地生成 但是限制Monster类型进入领地也许还需要EntityEvent
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityEvent.html

只要监听Monster位置在不在领地内 返回true就可以对Entity进行和移动权限监听一样的效果 我对插件并不太熟

**补充信息**

无

**Comment by ColdeZhang** [comment]
@365KW 如确认新功能无误请关闭此 issue
