### ISSUE TITLE
新增更多领地进出的提示方式

### ISSUE THREAD

**Issue by gghjgdyhtd** [ColdeZhang/Dominion#20]
**新功能是否和BUG有关？**

否

**新功能表述**

希望添加更多领地进出提示方式，比如bossBar，或者聊天框的提示，因为原本的领地进出提示用actionBar的纯白颜色提示方式不太显眼，特别是界面尺寸低的情况下，也容易与常驻actionBar提示的插件冲突

**Comment by ColdeZhang** [comment]
以下方案哪个更好一些？：
1. 在配置文件中配置提示消息显示区域（由服务器管理员控制显示位置）；
2. 领地设置增加显示区域配置（允许领地主自己决定显示位置）；

除此以外计划新增如下功能：
- 提示语增加彩色渲染支持；

**Comment by gghjgdyhtd** [comment]
> 以下方案哪个更好一些？：
> 
> 1. 在配置文件中配置提示消息显示区域（由服务器管理员控制显示位置）；
> 2. 领地设置增加显示区域配置（允许领地主自己决定显示位置）；
> 
> 除此以外计划新增如下功能：
> 
> * 提示语增加彩色渲染支持；

让管理员在配置文件中抉择吧，对于领地主人来说自己配置显示位置意义不大，且让每个领地的进出提示变得杂乱，反而是一种反效果

**Comment by ColdeZhang** [comment]
https://github.com/ColdeZhang/Dominion/blob/master/docs/zh-cn/operator/config.md#messagedisplay

此功能已在 [v2.8.0](https://github.com/ColdeZhang/Dominion/releases/tag/v2.8.0-beta) 实现，如验证无问题请关闭此 issue。
