### ISSUE TITLE
加入地皮模式。

### ISSUE THREAD

**Issue by cygbs** [ColdeZhang/Dominion#22]
**新功能是否和BUG有关？**

新功能与 Bug 无关。

**新功能表述**

在以前，地皮需要专门的插件来实现，并且需要一个新的世界作为地皮专用维度。我希望 Dominion 可以增加一个地皮模式，用于实现地皮的管理。具体来说，每个玩家可以领取一定数量的地皮，然后在特定地皮维度或者区域，他们可以使用这些地皮，但也只能在这里面建造。

我认为这个功能对于许多创造服务器有所帮助，如果添加了这个功能，也许 DOM 会更受欢迎。通过添加这个功能，创造服务器的地皮管理也将变得更加容易。

**新功能实现方案**

可以通过在现有领地功能的基础上添加一个地皮模式，例如可以将某个世界指定为地皮世界（或者在主世界内指定一块区域存放地皮）。

**补充信息**

无。

**Comment by yunshuangqwq** [comment]
附议！我也希望这个功能，不需要多负责只需要基本的地皮维度和和基本的功能

**Comment by ColdeZhang** [comment]
看描述不如直接安装地皮插件，然后设置指定的的世界为地皮世界

**Comment by yunshuangqwq** [comment]
不如dom好用咯～
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年09月22日 14:53 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [ColdeZhang/Dominion] 加入地皮模式。 (Issue #22) 
看描述不如直接安装地皮插件，然后设置指定的的世界为地皮世界

**Comment by ColdeZhang** [comment]
Dominion 未来将逐步提供 api，后续此类拓展功能可依靠外部插件实现
