### ISSUE TITLE
审核一下拉取请求qwq，补全了英文版开发者文档只翻译了一半的bug

### ISSUE THREAD

**Issue by yunshuangqwq** [ColdeZhang/Dominion#24]
**BUG描述**
审核一下拉取请求qwq，补全了英文版开发者文档只翻译了一半的bug

https://github.com/ColdeZhang/Dominion/pull/23
和
https://github.com/ColdeZhang/Dominion/pull/25

**Comment by ColdeZhang** [comment]
#23 #25 怎么关了？

**Comment by yunshuangqwq** [comment]
审核完了不关吗？
