### ISSUE TITLE
自定义领地最小长度

### ISSUE THREAD

**Issue by Charon2050** [ColdeZhang/Dominion#28]
**新功能和BUG无关。**

**新功能表述**

目前，对于非 OP 玩家，创建领地的最小大小为 4*4*4，若尝试创建过小的领地则会提示「领地的任意一边长度不得小于4」。这个数值似乎无法在 config.yml 中修改。希望可以支持修改这一数值，允许创建更小或仅限创建更大的领地。

**Comment by ColdeZhang** [comment]
该功能已在 2.11.0-beta be496aac 实现，如验证无问题请关闭此 issue

**Comment by Charon2050** [comment]
已在 Paper 1.21.1 上验证成功（哇你们更新效率好高）
