### ISSUE TITLE
装了Dominion启动不了服务器了！

### ISSUE THREAD

**Issue by yunshuangqwq** [ColdeZhang/Dominion#29]
**BUG描述**

装了Dominion启动不了服务器了，好久都没反应

**复现方式**

Bug复现步骤：

1. 安装Dominion插件
2. 启动服务器
3. 看着懵逼

**正常情况的表现**

正常情况下应该可以启动

**截图**

![Image_1728295629384.png](https://github.com/user-attachments/assets/1c9feb01-6fbd-4a66-80c8-708b618ab96f)

**运行环境:**

- 服务器系统：win
- 服务端核心：Paper
- 服务端版本：1.7.10
- 客户端版本：1.20.6
- 插件版本：最新的

**Comment by ColdeZhang** [comment]
请下载使用 full 后缀的版本

**Comment by yunshuangqwq** [comment]
那请问要这么下载，我不会呀！
