### ISSUE TITLE
无法连接bluemap

### ISSUE THREAD

**Issue by zhenruyan** [ColdeZhang/Dominion#31]
**BUG描述**

[06:56:34] [Folia Async Scheduler Thread #3/WARN]: [Dominion]  W | 无法连接 BlueMap 插件，如果你不打
算使用卫星地图渲染建议前往配置文件关闭此功能以避免下方的报错
[06:56:34] [Folia Async Scheduler Thread #3/ERROR]: [Dominion]  E | com/flowpowered/math/vector/Vect
or2d
[06:57:47]

**复现方式**

圈地的时候log报错  map中没有区域划分

**正常情况的表现**

正常情况下的表现应该是怎样的

**截图**

（可选）。

**运行环境:**

- 服务器系统：alpine 3.20 + arm64
- 服务端核心：paper
- 服务端版本：1.20.1
- 客户端版本：1.20.1
- 插件版本： - AuraSkills (2.2.4), BlueMap (5.4), Chunky (1.4.10), Dominion (2.14.0-beta), Essentials (2.20.1), 
EssentialsChat (2.20.1), SkinsRestorer (15.4.3)

**补充信息**

如错误日志等。

**Comment by ColdeZhang** [comment]
如报错信息提示，前往配置文件关闭 BlueMap 功能

```
BlueMap: false
```

**Comment by ColdeZhang** [comment]
该问题已在 v2.14.1-beta 8e490ec 修复

**Comment by zhenruyan** [comment]
> 请问java版本是多少？

zulu  jdk21

**Comment by zhenruyan** [comment]
> 该问题已在 v2.14.1-beta [8e490ec](https://github.com/ColdeZhang/Dominion/commit/8e490ec57af26852b0ea59577437d3cb0e0e769f) 修复
> 
> 如验证问题已解决请关闭此 issue

今晚会升级测试 谢谢
