### ISSUE TITLE
自动创建不会受vert配置的影响

### ISSUE THREAD

**Issue by BigAppleClass** [ColdeZhang/Dominion#33]
![6a815d3398627f52b972cf4f8d2be397](https://github.com/user-attachments/assets/afd9062d-0e5b-4635-8d3f-ab8510684cdb)
![8cfae5b7f7b854c8ac986c9ca55c5152](https://github.com/user-attachments/assets/03b7a59a-88f2-4ba9-8b55-3303bbd0c6af)
我向让玩家使用自动创建领地指令，领地半径是50，也就是一个100x100的正方形，然后高度是-64到380

**Comment by ColdeZhang** [comment]
提交bug建议按照模板填写相应内容

**Comment by ColdeZhang** [comment]
请问操作者是否是 OP？ 请试一下普通玩家创建领地是否存在问题

**Comment by ColdeZhang** [comment]
已在 cc90e5d 修复
