### ISSUE TITLE
即使拥有dominion.admin权限也不能打开管理面板

### ISSUE THREAD

**Issue by KaridaLee** [ColdeZhang/Dominion#39]
**BUG描述**

通过luckperm插件给予玩家dominion.admin权限也不能打开管理面板

**复现方式**

Bug复现步骤：

给予权限
输入dom
看不着管理面板

**正常情况的表现**

拥有dominion.admin的玩家输入dom指令看到的界面和操作权限和拥有op的玩家无异

**截图**

![01865ca6dbfccd1c7c255399aa4172f2](https://github.com/user-attachments/assets/042e3793-a62f-464a-9503-198cda3c6a1a)
![e80e787248aa5b54de9398d78fa38ad5](https://github.com/user-attachments/assets/2bb5a819-917a-418e-8b0d-087db4ddee0e)

**运行环境:**

- 服务器系统：winserver 2022
- 服务端核心：leaves
- 服务端版本：1.21.1
- 客户端版本：1.21.1
- 插件版本：2.14.6

**补充信息**

无日志

**Comment by ColdeZhang** [comment]
已在 2.14.7-beta 解决
