### ISSUE TITLE
游戏特性产生爆炸

### ISSUE THREAD

**Issue by 365KW** [ColdeZhang/Dominion#4]
**BUG描述**

对于熟悉 Minecraft的人都知道 特定的重生点设置器如果在其它维度使用会爆炸 而Dominion的领地并不能防止这种特性产生的爆炸 所以熊孩子们会在领地外爆破 把领地里的建筑"炸掉一层皮" 关闭tnt也会一样 需要限制 重生锚 和 床 在特定维度

**复现方式**

Bug复现步骤：

1. 前往主世界/末地领地
2. 在领地旁/内释放minecraft:tnt
3. 无法产生破坏
4. 在领地旁/内放置重生锚(下界可选床 末地可选床)
5. 充能
6. 达到最满后产生爆炸
7. 领地被破坏

**正常情况的表现**

和tnt creeper一样 建筑不会遭到破坏

**运行环境:**

- 服务器系统：windows 10
- 服务端核心：Spigot
- 服务端版本：1.21-Spigot
- 插件版本：v2.3.7

**Comment by ColdeZhang** [comment]
应该在 aa9065e 中修复

该权限控制合并到原领地环境中的 “生物破坏” ，现改名为 “生物破坏/非TNT爆炸”

手动删除 plugins 下的 flags.json 后会自动更新相关权限解释

**Comment by ColdeZhang** [comment]
https://github.com/ColdeZhang/Dominion/releases/tag/v2.3.8-beta

如验证bug已修复请关闭此 issue
