### ISSUE TITLE
在只拥有dominion.admin权限下不能打开其他领地管理页面

### ISSUE THREAD

**Issue by KaridaLee** [ColdeZhang/Dominion#43]
**BUG描述**

在只拥有dominion.admin权限、没有op的情况下不能打开其他领地管理页面

**复现方式**

Bug复现步骤：

去掉op并给予dominion.admin权限
不能点击/dom info界面内管理页面按钮

**正常情况的表现**

应该所有页面和操作都判断dominion.admin权限而不是op

**截图**

（可选）。

**运行环境:**

- 服务器系统：winserver-2022
- 服务端核心：leaves
- 服务端版本：leaves-1.21.1-81
- 客户端版本：1.21.1
- 插件版本：2.14.8

**补充信息**

如错误日志等。

**Comment by ColdeZhang** [comment]
已在 3.2.1 修复
