### ISSUE TITLE
长宽都必须配置为 0 才禁用领地创建功能

### ISSUE THREAD

**Issue by cygbs** [ColdeZhang/Dominion#45]
**BUG描述**

在配置文件中有一个配置领地大小的选项，注释描述其配置为 0 时将会禁止创建领地。当长为 0 或 宽为 0 而另一个长度不为 0 时，插件将允许创建领地。

**复现方式**

Bug复现步骤：

将配置文件中的长或宽修改成 0，重新加载发现还是可以创建领地。

**正常情况的表现**

只要长或宽为 0，则指定的世界不能创建任何领地。

**截图**

没有截图。

**运行环境:**

- 服务器系统：不知道
- 服务端核心：不知道
- 服务端版本：不知道
- 客户端版本：不知道
- 插件版本：不知道

**补充信息**

该问题是由于来自 Luminol 群内的提问而被发现的。

**Comment by ColdeZhang** [comment]
请提供详细的插件版本 服务器核心等内容

**Comment by ColdeZhang** [comment]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/104ccad6-216e-4aca-b593-88084748e2e1" />
 该问题在最新版无法复现
