### ISSUE TITLE
用类似于residence的GUI方式管理权限。

### ISSUE THREAD

**Issue by JellyBubb1e** [ColdeZhang/Dominion#46]
**新功能是否和BUG有关？**

无关。

**新功能表述**

目前用的是聊天栏来完成权限管理，需要来回滑动聊天栏来修改权限。目前权限还少，但是当权限管理数量增加后，聊天栏管理会越来越麻烦，通过箱子GUI管理，能够处理的权限密度增加，加快了修改权限速度。

**新功能实现方案**

通过箱子菜单来实现。

**补充信息**

唯一的问题是，GUI图标显示，不如文字直观，有可能会花大把时间来确认相关图标代表的权限是啥。

**Comment by ColdeZhang** [comment]
来回滑动？ 权限列表页面是有翻页功能的 可以直接翻页啊？

**Comment by JellyBubb1e** [comment]
翻页显示，显示权限密度也不够高。如果未来权限越做越多，可能会出现20多页这样子的情况。一个箱子页面能显示6*9，一页能直接看到52-53个权限。
