### ISSUE TITLE
实体移动权限🧐

### ISSUE THREAD

**Issue by 365KW** [ColdeZhang/Dominion#7]
**新功能是否和BUG有关？**

也许.😁

**新功能表述**

实体可以无视权限进入领地 最近 服务器出现了一群出生 把船 盔甲架 利用碰撞箱把实体撞飞进入领地 他们把这个利用了 来为玩家制造大麻烦 😰 我们需要一个 实体移动权限!

**新功能实现方案**

之前修复了(20.4更新) 也许 在领地里的 进入NoAI状态抑或是增加白名单 反正挺复杂的😱

**Comment by ColdeZhang** [comment]
这种人建议直接ban掉

监测这种非生物实体的移动代价相对来说比较大，而且由此可以引申出另一个熊服的东西就是实体挤压。你提到的“制造大麻烦”感觉就是领地内搞一堆实体，本质上和实体挤压是同一种熊服的东西。对于这种熊服有两种解决方法：

1. 直接给相关人ban掉，因为这种明显是主观恶意行为，不需要有任何留情的余地；
2. 安装实体限制相关的插件，防患于未然；

综上，目前不考虑在领地实现相关限制。
