### ISSUE TITLE
多语言的config.yml

### ISSUE THREAD

**Issue by 365KW** [ColdeZhang/Dominion#8]
**新功能是否和BUG有关？**

无

**新功能表述**

对config进行多语种支持 内销转出口不仅需要语言还要转换配置 flag.json也需要

**新功能实现方案**

内置语言文件+判断config.yml 亦或者i18n 或是人工翻译

**Comment by ColdeZhang** [comment]
config 支持多语言，相关翻译见对应语言文件的 Config.Comment 字段

**Comment by ColdeZhang** [comment]
flags.json 多语言涉及改动较多，目前优先对其他内容做 i18n 支持

**Comment by ColdeZhang** [comment]
flags已支持 i18n ，原 flags.json 迁移到 flags.yml，权限名称及描述迁移至语言文件的 Flags 段落。
